@startuml
'https://plantuml.com/activity-diagram-beta

start
partition Running{
repeat
:Wait for army turn;
partition Turn{
repeat
:Put the army on the map;
:Find neighbour;

repeat while (Is enemy solider your neighbour?) is (no);
:Fight;

}

repeat while(Stop condition met?) is (no);
}
stop
@enduml
