@startuml
'https://plantuml.com/sequence-diagram

autonumber

Solider->Solider :Move
activate Map
loop  until settlement impossible
Solider->Solider: generate random position
Solider->Map: Is the settlement possible?
Map->Solider: Answer
end
Map->Map: Move army to the location
 Map->Solider:Done
 deactivate Map

@enduml