@startuml
'https://plantuml.com/sequence-diagram

autonumber
[->Solider:Attack
activate Solider
Solider-->Map:Get enemy neighbours
Map-->Solider: List of the neighbours
loop While  In list of neighbours we have soliders
Solider-->Solider: choose random enemy
Solider-->EnemySolider:Check if enemy
EnemySolider-->Solider:answer
group If [is enemy]
Solider->Arena:perform fight

end

Arena->Solider : Name of killed
end
<-Solider:Done

deactivate Solider


@enduml