@startuml
'https://plantuml.com/state-diagram


[*] --> Initialised

state Initialised
Initialised --> Assigned:Assign to army
Assigned --> SettledDown: settle down
SettledDown -->Wait:Put soliders on map
Wait:wait for solider's turn
Wait-->Checking



Checking:Check if enemy soliders
Checking:is your neighbour
Checking-->Move: no
Checking--> Choose: yes
Choose:choose random neighbour
Move-->Choose
Choose-->attack
attack:attack enemy
attack-->Checking2
Checking2:chceck if hp<0
Checking2-->attack: no
Checking2-->kill: yes
kill-->Checking3
Checking3: check if u have neighbour
Checking3->Choose: yes
Checking3-->Wait









}
@enduml